  version: '2.0'
  services:
  
#pHP
   app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nielae/php-cli

    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel-app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - laravel-realworld-network
 
  #Nginx Service
   webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-realworld-network

  #MySQL
   db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: niela
      MYSQL_USER: niela
      MYSQL_ROOT: nielar
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-realworld-network

  #networks
  networks:
    laravel-realworld-network:
        driver: bridge

  volumes:
    mysql:
      driver: local
